### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by LIULIUUUU** [GuangchuangYu/yyplot#1]
您好，
[非常感谢您的代码！但是下载您的压缩包之后，我发现无法安装成功。不知道是不是不支持的问题，R3.4.1和3.4.2我都试过，使用
install.packages("yyplot")
出现的是下面这段运行结果
Installing package into ‘C:/Users/LIUUU/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘yyplot’ is not available (for R version 3.4.2)
希望向您请教，十分感谢！

**Comment by GuangchuangYu** [comment]
```
devtools::install_github('GuangchuangYu/yyplot')
```

**Comment by LIULIUUUU** [comment]
非常感谢！

**Comment by derek926** [comment]
你好，参见上面的方法失效，请问还能如何操作才能安装上呢？
> devtools::install_github('GuangchuangYu/yyplot')
Downloading GitHub repo GuangchuangYu/yyplot@master
Downloading GitHub repo GuangchuangYu/gglayer@master
Skipping 1 packages not available: ggtree
√  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpMnUBWD\remotes101cc392b526b\GuangchuangYu-gglayer-15df082/DESCRIPTION' (490ms)
-  preparing 'gglayer':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'gglayer_0.0.1.tar.gz'
   
* installing *source* package 'gglayer' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'setup_data_continuous_color' not found
Error: unable to load R code in package 'gglayer'
Execution halted
ERROR: lazy loading failed for package 'gglayer'
* removing 'D:/Rsoftware/R-3.6.1/library/gglayer'
Error: Failed to install 'yyplot' from GitHub:
  Failed to install 'gglayer' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpMnUBWD/file101cc6bdc3911/gglayer_0.0.1.tar.gz’ had non-zero exit status

**Comment by GuangchuangYu** [comment]
需要ggtree 2.0.0

**Comment by derek926** [comment]
done! thx Prof Yu!
